# Team Trials tierlist explanations
tt_explanations = {
    # Speed Skills - TT
    "[Run Style] Corners ◯": "Cheap and consistent, they are must-haves",
    "[Run Style] Straightaways ◯": "Cheap and consistent, they are must-haves", 
    "[Run Style] Corners ◎": "Cheap and consistent, they are must-haves",
    "[Distance] Corners ◯": "Cheap and consistent, they are must-haves",
    "[Run Style] Straightaways ◎": "Cheap and consistent, they are must-haves",
    "[Distance] Straightaways ◯": "Cheap and consistent, they are must-haves",
    "[Distance] Corners ◎": "Cheap and consistent, they are must-haves",
    "[Distance] Straightaways ◎": "Cheap and consistent, they are must-haves",
    "Uma Stan": "Good speed skill, can help to release PDM on some longer tracks",
    "Uma Mania": "Good speed skill, can help to release PDM on some longer tracks",
    "Tail Held High": "Cheap and consistent, though note the condition of requiring 3 skill activations before acquiring it",
    "Slipstream": "Consistent and facilitates overtaking when activated",
    "Playtime's Over!": "Consistent and improves Uma's capacity to maintain her placement",
    "Burning Spirit GUTS": "Good random Late-Race accel but in the game's current state, this skill's effect is likely 80% (when Total Guts ≤ 1200) or 90% (when 1200 < Total Guts ≤ 1600)",
    "Fast-Paced": "Consistent with easy conditions. Helps Front Runners maintain/regain their lead during the Mid-Race",
    "Escape Artist": "Consistent with easy conditions. Helps Front Runners maintain/regain their lead during the Mid-Race",
    "1,500,000 CC": "Cheap and consistent",
    "Mile Maven": "Mostly consistent but activation occurs during Early-Race where Uma may not have hit top speed, making target speed boosts obsolete (doesn't actually increase speed since Uma's Current Speed hasn't reached Target Speed). Additionally, the skill may pick a point prior to the 5 seconds needed after the race starts to activate, making it proc inconsistently too",
    "Unyielding Spirit": "Cheap and consistent",
    "Fast & Furious": "Consistent",
    "Big-Sisterly": "Cheap and consistent",
    "Outer Swell": "Somewhat consistent but Target Speed boost during Final Corners are only useful if Uma will enter Last Spurt Mode in a few seconds/has already entered Last Spurt Mode. Otherwise, boosting Target Speed right when Uma enters Last Spurt Mode renders it useless (doesn't actually increase speed since Uma's Current Speed hasn't reached Target Speed)",
    "Rising Dragon": "Somewhat consistent but Target Speed boost during Final Corners are only useful if Uma will enter Last Spurt Mode in a few seconds/has already entered Last Spurt Mode. Otherwise, boosting Target Speed right when Uma enters Last Spurt Mode renders it useless (doesn't actually increase speed since Uma's Current Speed hasn't reached Target Speed)",
    "Changing Gears": "Consistent",
    "Certain Victory": "Identical to OG Teio's unique with slightly looser conditions",
    "Sky-High Teio Step": "Mostly consistent for non-Front-Runners, with strong effect",
    "Triumphant Pulse": "Consistent for non-Front-Runners, with strong effect", 
    "Behold Thine Emperor's Divine Might": "Consistent for non-Front-Runners, with strong effect",
    "Lights of Vaudeville": "Consistent activation but effectiveness depends on track",
    "Professor of Curvature": "Consistent, but expensive. Rare ver. has greater speed boost making it more worth to acquire",
    "Beeline Burst": "Duration is only 0.9s, but consistent activation so still usable. Rare ver. increases speed boost effect but it's still plagued by its abysmal 0.9s base duration",
    "Ramp Up": "Consistent. Even better when used in tandem with Tail Held High, Slipstream, and Playtime's Over!",
    "It's On!": "Consistent. Even better when used in tandem with Tail Held High, Slipstream, and Playtime's Over!",
    "Homestretch Haste": "Useful and (fairly) consistent Last Spurt speed boost, falls short of ◎ because it could activate at the very end of a race",
    "In Body and Mind": "Useful and (fairly) consistent Last Spurt speed boost, falls short of ◎ because it could activate at the very end of a race",
    "Ignited Spirit GUTS": "Good random Late-Race accel but in the game's current state, this skill's effect is likely 80% (when Total Guts ≤ 1200) or 90% (when 1200 < Total Guts ≤ 1600)",
    "[Rotation]-Handed ◯": "Speed stat increase is significant",
    "[Rotation]-Handed ◎": "Speed stat increase is significant",
    "[Season] Runner ◯": "Speed stat increase is significant",
    "[Season] Runner ◎": "Speed stat increase is significant", 
    "Lone Wolf": "Easy to proc, you either benefit (you proc) or make it even (you prevent someone else's from proc'ing)",
    "Position Pilfer": "Consistent",
    "Productive Plan": "Mostly consistent but activation occurs during Early-Race where Uma may not have hit top speed, making target speed boosts obsolete (doesn't actually increase speed since Uma's Current Speed hasn't reached Target Speed). Additionally, the skill may pick a point prior to the 5 seconds needed after the race starts to activate, making it proc inconsistently too",
    "Shifting Gears": "Consistent",
    "Up-Tempo": "Consistent",
    "Killer Tunes": "Consistent",
    "Ignited Spirit SPD": "1.8s isn't very long and it costs 200 base SP",
    "Burning Spirit SPD": "1.8s isn't very long and it costs 200 base SP",
    "Leader's Pride": "Inconsistent activation during Early-Race where overtaking doesn't happen frequently or consistently, consistency is directly proportional to track distance",
    "Speed Star": "Consistent but Target Speed boost during Final Corners are only useful if Uma will enter Last Spurt Mode in a few seconds/has already entered Last Spurt Mode. Otherwise, boosting Target Speed right when Uma enters Last Spurt Mode renders it useless (doesn't actually increase speed since Uma's Current Speed hasn't reached Target Speed)",
    
    # Acceleration Skills - TT
    "Corner Acceleration ◯": "Acceleration on the Corner 1/First Corner of any track is useless",
    "Corner Connoisseur": "Acceleration on the Corner 1/First Corner of any track is useless",
    "Straightaway Acceleration": "Random straight activations are too inconsistent to be effective",
    "Rushing Gale!": "Random straight activations are too inconsistent to be effective",
    "Nimble Navigator": "Strong accel but rng-dependent",
    "No Stopping Me!": "Strong accel but rng-dependent",
    "Highlander": "Very powerful on tracks with Uphills right before/as Last Spurt Mode begins",
    "Groundwork": "For Front Runners only, use with 3 Early-Race skills like Focus/Concentration+Green Skills",
    "Ignited Spirit PWR": "It's like a weaker but universal Slick Surge/On Your Left!",
    "Burning Spirit PWR": "It's like a weaker but universal Slick Surge/On Your Left!",
    "Early Lead": "Necessary skill for all Front Runners",
    "Taking the Lead": "Necessary skill for all Front Runners",
    "Final Push": "Being in 1st isn't completely consistent, but it's a rare skill that can be useful on tracks where your Uma enters Last Spurt Mode slightly after where the Final Corner begins/right at where the Final Corner is",
    "Unrestrained": "Being in 1st isn't completely consistent, but it's a rare skill that can be useful on tracks where your Uma enters Last Spurt Mode slightly after where the Final Corner begins/right at where the Final Corner is",
    "Second Wind": "Expensive and impossible to activate on Front Runners, plus, Mid-Race acceleration is useless",
    "Shrewd Step": "Cheap and consistent activation, but useless Mid-Race accel",
    "Technician": "Cheap and consistent activation, but useless Mid-Race accel",
    "Straight Descent": "Very powerful on tracks with Downhills right before/as Last Spurt Mode begins",
    "Determined Descent": "Very powerful on tracks with Downhills right before/as Last Spurt Mode begins",
    "Tactical Tweak": "Cheap and consistent activation, but useless Mid-Race accel",
    "Shatterproof": "Cheap and consistent activation, but useless Mid-Race accel",
    "Head-On": "Pace Chaser ver. of Slick Surge",
    "Slick Surge": "Good but inconsistently effective accel",
    "On Your Left!": "Good but inconsistently effective accel",
    "Fighter": "Cheap and consistent activation but useless Mid-Race accel",
    "Hard Worker": "Cheap and consistent activation but useless Mid-Race accel",
    "Straightaway Spurt": "Very powerful End Closer acceleration that works on tracks where Last Spurt Mode begins on a Straight",
    "Encroaching Shadow": "Very powerful End Closer acceleration that works on tracks where Last Spurt Mode begins on a Straight",
    "Sprinting Gear": "Random straight activations are almost always useless",
    "Turbo Sprint": "Random straight activations are almost always useless",
    "Countermeasure": "Gamble accel, if it procs right before Mid-Race ends it'll be effective",
    "Plan X": "Gamble accel, if it procs right before Mid-Race ends it'll be effective",
    "Updrafters": "Good but inconsistently effective accel for Lates/Ends in Mile",
    "Furious Feat": "Good but inconsistently effective accel for Lates/Ends in Mile",
    "Acceleration": "Fairly consistent but Mid-Race accel is useless",
    "Step on the Gas!": "Fairly consistent but Mid-Race accel is useless",
    "Red Shift/LP1211-M": "Powerful accel for Fronts/Paces, especially on tracks where Last Spurt Mode begins slightly before or on the Final Corner",
    "Shooting for Victory!": "Powerful accel for Paces/Lates, especially on tracks where Last Spurt Mode begins slightly before or on the Second Half of the Final Corner",
    "Let's Pump Some Iron!": "Strongest but most inconsistent accel for Lates/Ends on tracks where Last Spurt Mode begins slightly before or on the Final Corner",
    "Angling and Scheming": "Strongest accel for Fronts on tracks where Last Spurt Mode begins on a Corner",
    "Condor's Fury": "Powerful accel for Lates/Ends, especially on tracks where Last Spurt Mode begins slightly before or on the Final Corner",
    "KEEP IT REAL.": "Mostly useless accel but consistent activation",

    # Recovery (Stamina) Skills - TT
    "Corner Recovery ◯": "Consistent and effective recovery",
    "Swinging Maestro": "Consistent and effective recovery",
    "Preferred Position": "Consistent and effective recovery",
    "Race Planner": "Consistent and effective recovery",
    "Hydrate": "Consistent and effective recovery",
    "Gourmand": "Consistent and effective recovery",
    "Calm and Collected": "Stamina to Spare is okay as its recovery is unlikely to overflow (making it a decent choice), but Calm and Collected may recover too much in a few situations (making it less consistent)",
    "Straightaway Recovery": "Inconsistent, it might be wasted on an early or late activation",
    "Breath of Fresh Air": "Inconsistent, it might be wasted on an early or late activation",
    "Lay Low": "Might proc in Early-Race which might overflow HP",
    "Iron Will": "Might proc in Early-Race which might overflow HP",
    "Pace Strategy": "Being overtaken is an inconsistent condition. More suitable on long, backline Run Styles",
    "Indomitable": "Being overtaken is an inconsistent condition. More suitable on long, backline Run Styles",
    "Calm in a Crowd": "Almost impossible to be boxed in on all sides",
    "Unruffled": "Almost impossible to be boxed in on all sides",
    "Triple 7s": "Consistent, but only effective on <2400m tracks, useful for some Uma that rely on Stamina skill procs",
    "Shake It Out": "Late-Race recovery is ineffective but very cheap for Team Trials",
    "Ignited Spirit STA": "Definitely an option but it costs more than a usual skill (at 200 base SP)",
    "Burning Spirit STA": "Definitely an option but it costs more than a usual skill (at 200 base SP)",
    "Moxie": "Consistent activation but recovery can be useless when the uphill is located at anywhere other than Mid-Race",
    "Restless": "Consistent activation but recovery can be useless when the uphill is located at anywhere other than Mid-Race",
    "Stamina to Spare": "Stamina to Spare is okay as its recovery is unlikely to overflow (making it a decent choice), but Calm and Collected may recover too much in a few situations (making it less consistent)",
    "A Small Breather": "Late-Race recovery is ineffective, Last Spurt recalculation isn't added until 1st Year Anniversary",
    "Relax": "Late-Race recovery is ineffective, Last Spurt recalculation isn't added until 1st Year Anniversary",
    "Standing By": "Somewhat consistent, but may be undesirable for well-built End Closers since they can probably reach positions above 75% by distance and hence, not activate this skill",
    "Sleeping Lion": "Somewhat consistent, but may be undesirable for well-built End Closers since they can probably reach positions above 75% by distance and hence, not activate this skill",
    "After-School Stroll": "Consistent activation but recovery can be useless when the downhill is located at anywhere other than Mid-Race",
    "Go-Home Specialist": "Consistent activation but recovery can be useless when the downhill is located at anywhere other than Mid-Race",
    "Levelheaded": "Getting blocked is a decently consistent condition for End Closers",
    "Wait-and-See": "Only for Late Surgers/End Closers (only King Halo for now), the extra acceleration effect is useless",
    "Watchful Eye": "Most effective Mile debuff skill, must-have for all Mile debuffers",
    "Keen Eye": "Most effective Mile debuff skill, must-have for all Mile debuffers",
    "Rosy Outlook": "Consistent recovery for Front Runners and perhaps even Pace Chasers",
    "Trackblazer": "Consistent recovery for Front Runners and perhaps even Pace Chasers",
    "Soft Step": "Consistent but effect isn't that strong. Rare ver. is actually worse as this tends to activate early on and the 5.5% recovery could overflow",
    "Miraculous Step": "Consistent but effect isn't that strong. Rare ver. is actually worse as this tends to activate early on and the 5.5% recovery could overflow",
    "Deep Breaths": "Inconsistent, it might be wasted on an early or late activation",
    "Cooldown": "Inconsistent, it might be wasted on an early or late activation",
    "Extra Tank": "If your HP drops to zero, you're cooked anyway, no recovery can save you",
    "Adrenaline Rush": "If your HP drops to zero, you're cooked anyway, no recovery can save you",
    "Passing Pro": "Mostly consistent but activation can occur on Early-Race, diminishing its value",
    "U=ma2": "They cost a whopping 200 SP for 1.5% recovery. It's more worth to inherit other uniques. The only exceptions right now are Super Creek's and Grass Wonder (Fantasy)'s",
    "Pure Heart": "They cost a whopping 200 SP for 1.5% recovery. It's more worth to inherit other uniques. The only exceptions right now are Super Creek's and Grass Wonder (Fantasy)'s",
    "Super-Duper Climax": "They cost a whopping 200 SP for 1.5% recovery. It's more worth to inherit other uniques. The only exceptions right now are Super Creek's and Grass Wonder (Fantasy)'s",
    "Superior Heal": "They cost a whopping 200 SP for 1.5% recovery. It's more worth to inherit other uniques. The only exceptions right now are Super Creek's and Grass Wonder (Fantasy)'s",
    "Dazzl'n ♪ Diver": "They cost a whopping 200 SP for 1.5% recovery. It's more worth to inherit other uniques. The only exceptions right now are Super Creek's and Grass Wonder (Fantasy)'s",

        # Other Skills (Lane Movement/FoV/Start/Green) - TT
    "Prudent Positioning": "Use with Dodging Danger for a very powerful Early-Race burst of speed (Front Runner only)",
    "Center Stage": "Never use for Front-Runners that want to run the Dodging Danger tech",
    "Go with the Flow": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. Take only because they are very cheap and if you have no other options",
    "Lane Legerdemain": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. Take only because they are very cheap and if you have no other options",
    "Ignited Spirit WIT": "Use with Dodging Danger for a very powerful Early-Race burst of speed (Front Runner only)",
    "Burning Spirit WIT": "Never use for Front-Runners that want to run the Dodging Danger tech",
    "Dodging Danger": "Use with Prudent Positioning/Ignition Spirit WIT for a very powerful Early-Race burst of speed (Front Runner only)",
    "Sixth Sense": "Never use for Front-Runners that want to run the 'Prudent Positioning' + 'Dodging Danger' combo",
    "Meticulous Measures": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. There is no need for any additional acceleration (unless it's toward the very end which is very RNG-dependent). Take only because they are very cheap and if you have no other options",
    "Perfect Prep!": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. There is no need for any additional acceleration (unless it's toward the very end which is very RNG-dependent). Take only because they are very cheap and if you have no other options",
    "Thunderbolt Step": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. There is no need for any additional acceleration (unless it's toward the very end which is very RNG-dependent). Take only because they are very cheap and if you have no other options",
    "Lightning Step": "Random non-Early-Race Lane Movement Speed for non-Front-Runners are useless. There is no need for any additional acceleration (unless it's toward the very end which is very RNG-dependent). Take only because they are very cheap and if you have no other options",
    "Focus": "Only take for Front Runners, Focus reduces the chance of a Late Start, while Concentration makes it impossible. You also get score for 'strong starts' in Team Trials, so Concentration is always good there",
    "Concentration": "Only take for Front Runners, Focus reduces the chance of a Late Start, while Concentration makes it impossible. You also get score for 'strong starts' in Team Trials, so Concentration is always good there",
    "Studious": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "The Bigger Picture": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "I Can See Right Through You": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "The Coast Is Clear!": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "Strategist": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "Crusader": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "Hawkeye": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "Clairvoyance": "Extra FoV is mostly useless. Take only because they are very cheap and if you have no other options",
    "Runaway": "Dependent on what you want/need",
    "[Location] Racecourse ◯": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "[Location] Racecourse ◎": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "Standard Distance ◯": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "Standard Distance ◎": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "Non-Standard Distance ◯": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "Non-Standard Distance ◎": "Stamina stat increase is good but not completely necessary unless you're short of stamina",
    "[Ground Condition] Conditions ◯": "Power Stat increase is decent but low priority",
    "[Ground Condition] Conditions ◎": "Power Stat increase is decent but low priority",
    "[Weather] Days ◯": "Guts is extremely unimportant, only take it you really need to",
    "[Weather] Days ◎": "Guts is extremely unimportant, only take it you really need to",
    "[Run Style] Savvy ◯": "Consistent activation, FoV buff is useful for Nice Nature's All-Seeing Eyes",
    "[Run Style] Savvy ◎": "Consistent activation, FoV buff is useful for Nice Nature's All-Seeing Eyes",
    "Outer Post Proficiency ◯": "Post Numbers 6-8 is inconsistent",
    "Outer Post Proficiency ◎": "Post Numbers 6-8 is inconsistent",
    "Maverick ◯": "Very rare to have no Umas use your run style",
    "Maverick ◎": "Very rare to have no Umas use your run style",
    "Long Shot ◯": "Popularity-dependent skills are inconsistent",
    "Long Shot ◎": "Popularity-dependent skills are inconsistent",
    "Sympathy": "Practically impossible to proc",
    "Competitive Spirit ◯": "It's unlikely for 40% of the lobby to use the same run style as you",
    "Competitive Spirit ◎": "It's unlikely for 40% of the lobby to use the same run style as you",
    "Target in Sight ◯": "1st Fav. uses the same [Run Style] as you",
    "Target in Sight ◎": "1st Fav. uses the same [Run Style] as you",
    "Inner Post Proficiency ◯": "Post Numbers 1-3 is inconsistent",
    "Inner Post Proficiency ◎": "Post Numbers 1-3 is inconsistent",
    "Lucky Seven": "Inconsistent, even more so than the Post Proficiency skills",
    "Super Lucky Seven": "Inconsistent, even more so than the Post Proficiency skills",
}