"""
War Thunder Aircraft Database
Structure for each Aircraft:
{'name': str, 'br': float, 'type': str, 'nation': str, 'premium': bool}
Vehicle types: fighter, strike fighter, bomber, helicopter (intercepters are considered fighters)
"""

usa_aircraft = [
    # Rank I - Researchable
    {'name': 'P-26A-34 M2', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-36A', 'br': 1.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'BF2C-1', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'OS2U-1', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'OS2U-3', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'TBD-1', 'br': 1.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'B-18A', 'br': 1.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-26A-33', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-26B-35', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-36C', 'br': 1.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F3F-2', 'br': 1.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'SB2U-2', 'br': 1.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'SB2U-3', 'br': 1.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'PBY-5 Catalina', 'br': 1.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'PBY-5A Catalina', 'br': 1.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'F2A-1', 'br': 2.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'TBF-1C', 'br': 1.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'SBD-3', 'br': 2.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'PBM-1 "Mariner"', 'br': 2.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},

    # Rank I - Premium
    {'name': "Galer's F3F-2", 'br': 1.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-26A-34', 'br': 1.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '○P-36C', 'br': 1.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': "Rasmussen's P-36A", 'br': 1.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': "Thach's F2A-1", 'br': 2.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'B-10B', 'br': 1.3, 'type': 'bomber', 'nation': 'usa', 'premium': True},

    # Rank II - Researchable
    {'name': 'P-400', 'br': 2.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-36G', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F2A-3', 'br': 2.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-36', 'br': 2.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-34', 'br': 3.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-38E', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-38G-1', 'br': 3.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-40E-1', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-40F-10', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4F-3', 'br': 2.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4F-4', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F6F-5', 'br': 3.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-20G-25', 'br': 2.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-25J-1', 'br': 3.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-39N-0', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-39Q-5', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-51C-10', 'br': 3.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-1A', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-1A (USMC)', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-1D', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'SB2C-1C', 'br': 3.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'SB2C-4', 'br': 3.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-25J-20', 'br': 3.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},

    # Rank II - Premium
    {'name': 'P-40E-1 TD', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-40C', 'br': 2.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '▃Ki-43-II', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'YP-38', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-51A', 'br': 3.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-43A-1', 'br': 2.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'XP-38G', 'br': 3.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'PBM-3 "Mariner"', 'br': 3.0, 'type': 'bomber', 'nation': 'usa', 'premium': True},
    {'name': '▃Ki-61-Ib', 'br': 3.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},

    # Rank III - Researchable
    {'name': 'P-63A-5', 'br': 3.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-51', 'br': 3.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-51D-5', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-4', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'PBJ-1J', 'br': 3.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'PBJ-1H', 'br': 3.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-26B', 'br': 4.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-63A-10', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-63C-5', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-47D-22-RE', 'br': 3.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-47D-25', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F8F-1', 'br': 4.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-61C-1', 'br': 4.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-17E', 'br': 4.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'B-17E/L', 'br': 5.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-38J-15', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-38L-5-LO', 'br': 4.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-47D-28', 'br': 4.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-47N-15', 'br': 4.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F6F-5N', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'PB4Y-2', 'br': 4.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},

    # Rank III - Premium
    {'name': '▃A6M2', 'br': 3.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'XF5F', 'br': 2.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'BTD-1', 'br': 4.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-61A-11', 'br': 3.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'XP-55', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'PV-2D', 'br': 3.7, 'type': 'bomber', 'nation': 'usa', 'premium': True},
    {'name': 'XP-50', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '␠Kingcobra', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '▃Bf 109 F-4', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'PBM-5A "Mariner"', 'br': 3.3, 'type': 'bomber', 'nation': 'usa', 'premium': True},

    # Rank IV - Researchable
    {'name': 'F-82E', 'br': 5.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'P-51D-30', 'br': 5.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-1C', 'br': 4.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F4U-4B', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-26B-10', 'br': 5.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-26B-50', 'br': 5.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-17G-60-VE', 'br': 5.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'B-24D-25-CO', 'br': 5.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'P-51H-5-NA', 'br': 6.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F8F-1B', 'br': 6.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F7F-1', 'br': 6.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'AD-2', 'br': 5.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'AD-4', 'br': 6.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'AM-1', 'br': 5.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-29A-BN', 'br': 7.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},

    # Rank IV - Premium
    {'name': 'XA-38', 'br': 3.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': "Bong's P-38J-15", 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-51D-20-NA', 'br': 4.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-38K', 'br': 5.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-51D-10', 'br': 4.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-26C-45', 'br': 5.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-47M-1-RE', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-26C-45DT', 'br': 5.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': '⋠P-47M-1-RE', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'P-59A', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '▃Fw 190 A-8', 'br': 5.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F4U-4B VMF-214', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '▃Spitfire LF Mk IXc', 'br': 5.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'AU-1', 'br': 5.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-1H', 'br': 6.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F2G-1', 'br': 6.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F7F-3', 'br': 6.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},

    # Rank V - Researchable
    {'name': 'F-80A-5', 'br': 7.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-84B-26', 'br': 7.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-84G-21-RE', 'br': 7.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F2H-2', 'br': 7.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F3D-1', 'br': 7.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-57A', 'br': 8.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'B-57B', 'br': 8.3, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'F-80C-10', 'br': 7.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-86A-5', 'br': 8.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-86F-25', 'br': 8.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F9F-2', 'br': 8.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F9F-5', 'br': 8.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F9F-8', 'br': 8.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-84F', 'br': 8.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},

    # Rank V - Premium
    {'name': 'F-89B', 'br': 7.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A2D-1', 'br': 7.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-89D', 'br': 7.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-86F-35', 'br': 8.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},

    # Rank VI - Researchable
    {'name': 'F-104A', 'br': 9.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-104C', 'br': 9.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-86F-2', 'br': 8.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F3H-2', 'br': 9.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-4B', 'br': 8.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'FJ-4B', 'br': 8.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'B-66B', 'br': 9.0, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'F-100D', 'br': 9.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F8U-2', 'br': 10.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'AV-8C', 'br': 9.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},

    # Rank VI - Premium/Squadron
    {'name': 'A-4E Early', 'br': 8.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'FJ-4B VMF-232', 'br': 8.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-117', 'br': 8.7, 'type': 'bomber', 'nation': 'usa', 'premium': True},
    {'name': 'F11F-1', 'br': 9.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'AV-8A', 'br': 9.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F4D-1', 'br': 9.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-10A', 'br': 10.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-106A', 'br': 9.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},

    # Rank VII - Researchable
    {'name': 'F-5E', 'br': 11.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-4C Phantom II', 'br': 10.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-8E', 'br': 10.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-10A Late', 'br': 10.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-105D', 'br': 10.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-4E Phantom II', 'br': 11.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-4J Phantom II', 'br': 12.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-7D', 'br': 10.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'A-7E', 'br': 10.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-111A', 'br': 10.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},
    {'name': 'A-10C', 'br': 11.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-111F', 'br': 11.7, 'type': 'bomber', 'nation': 'usa', 'premium': False},

    # Rank VII - Premium
    {'name': 'F-5C', 'br': 10.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-5A', 'br': 10.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-6E TRAM', 'br': 10.7, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'A-7K', 'br': 11.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F-4S Phantom II', 'br': 12.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'AV-8B (NA)', 'br': 11.3, 'type': 'strike fighter', 'nation': 'usa', 'premium': True},

    # Rank VIII - Researchable
    {'name': 'F-16A', 'br': 12.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-16A ADF', 'br': 13.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-15A', 'br': 13.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F/A-18A', 'br': 12.3, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'AV-8B Plus', 'br': 13.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-15E', 'br': 14.0, 'type': 'strike fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-16C', 'br': 13.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-15C MSIP II', 'br': 13.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-14A Early', 'br': 12.7, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F-14B', 'br': 13.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},
    {'name': 'F/A-18C Late', 'br': 14.0, 'type': 'fighter', 'nation': 'usa', 'premium': False},

    # Rank VIII - Premium
    {'name': 'F-20A', 'br': 12.3, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': '▄F-14A IRIAF', 'br': 13.0, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    {'name': 'F/A-18C Early', 'br': 12.7, 'type': 'fighter', 'nation': 'usa', 'premium': True},
    
    # Rank V Helicopters - Researchable
    {'name': 'AH-1G', 'br': 8.0, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'UH-1B', 'br': 8.3, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'UH-1C', 'br': 8.7, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    
    # Rank V Helicopters - Premium
    {'name': 'H-34', 'br': 7.7, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    {'name': 'UH-1C XM-30', 'br': 8.7, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    
    # Rank VI Helicopters - Researchable
    {'name': 'AH-6M', 'br': 10.3, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-1F', 'br': 9.7, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'OH-58D', 'br': 10.3, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-64A', 'br': 11.7, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-1W', 'br': 11.0, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    
    # Rank VI Helicopters - Premium/Squadron
    {'name': 'YAH-64', 'br': 11.3, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    {'name': '▃AH-64A Peten', 'br': 11.7, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    {'name': 'AH-64A (GR)', 'br': 11.7, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    {'name': 'RAH-66', 'br': 11.3, 'type': 'helicopter', 'nation': 'usa', 'premium': True},
    
    # Rank VII Helicopters - Researchable
    {'name': 'MH-60L DAP', 'br': 11.3, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-64D', 'br': 12.0, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-1Z', 'br': 12.0, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
    {'name': 'AH-64E', 'br': 13.0, 'type': 'helicopter', 'nation': 'usa', 'premium': False},
]

germany_aircraft = [
    # Rank I
    {'name': 'Bf 109 B-1', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 51 A-1', 'br': 1.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 51 B-1', 'br': 1.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 51 C-1', 'br': 1.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 51 C-1/L', 'br': 1.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 17 Z-7', 'br': 1.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Hs 123 A-1', 'br': 1.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 17 E-1', 'br': 1.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Do 17 Z-2', 'br': 1.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 C-1', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 112 V-5', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 112 A-0', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 J-1', 'br': 2.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 J-2', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 B-2', 'br': 1.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 R-2', 'br': 1.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 115 C-1', 'br': 1.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'BV 138 C-1', 'br': 1.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'He 100 D-1', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 G-1', 'br': 1.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 G-2', 'br': 1.7, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 111 H-3', 'br': 2.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    
    # Rank I Premium
    {'name': 'Flegel\'s Bf 109 A', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'He 51 B-2/H', 'br': 1.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Ju 87 R-2 Libya', 'br': 1.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Ar 196 A-3', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Marcolin\'s C.R.42 CN', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Fw 189 A-1', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'CR.42', 'br': 1.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'G.50 serie 2', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'G.50 AS serie 7', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 109 C-1', 'br': 1.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'C. 200 serie 3', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'C. 200 serie 7', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'C. 202', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    
    # Rank II
    {'name': 'Bf 109 E-1', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 112 B-0', 'br': 2.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 88 C-6', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Hs 129 B-3', 'br': 2.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Hs 129 B-2', 'br': 2.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 200 C-1', 'br': 2.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 E-3', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 E-4', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'С-3604', 'br': 2.7, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 N-1', 'br': 2.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 N-2', 'br': 2.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 D-3', 'br': 2.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 87 D-5', 'br': 3.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 88 A-1', 'br': 2.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 88 A-4', 'br': 3.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 F-1', 'br': 2.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 F-2', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-1', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 110 C-7', 'br': 2.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 110 F-2', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 A-1/U4', 'br': 2.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 B-2/U4', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 111 H-6', 'br': 2.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'He 111 H-16', 'br': 3.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    
    # Rank II Premium
    {'name': 'He 112 B-1/U2', 'br': 2.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Wellington Mk Ic', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'IL-2 (1942)', 'br': 3.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'He 112 B-2/U2', 'br': 2.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 109 T-2', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Hawk H-75A-2', 'br': 2.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 110 C-6', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 109 E-7/U2', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Yak-1B', 'br': 3.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 serie 1', 'br': 1.7, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 serie 8', 'br': 2.0, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 AS', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 bis/T.M', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 B', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 serie 4', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'S.M.79 bis/N', 'br': 2.3, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'BV 238', 'br': 3.7, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    
    # Rank III
    {'name': 'Bf 109 F-4', 'br': 4.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 F-4/trop', 'br': 4.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-4', 'br': 4.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-5/U2', 'br': 4.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 110 G-2', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 110 G-4', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 A-1', 'br': 3.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 B-1', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 264', 'br': 5.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 D-9', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 A-1/U2', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 B-1/U2', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 335 A-1', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 335 A-0', 'br': 4.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 E-2', 'br': 4.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 E-4', 'br': 4.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    
    # Rank III Premium
    {'name': 'P-47D-16-RE', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Hs 129 B-2 (Romania)', 'br': 2.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Ta 154 A-1', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'P-47D', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Fw 190 A-5/U14', 'br': 4.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'La-5FN', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 109 G-2', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'BV 155 B-1', 'br': 3.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    
    # Rank IV
    {'name': 'Bf 109 G-2/trop', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 G-6', 'br': 4.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-5', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-8', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 410 B-6/R3', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 F-8', 'br': 5.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 K-1', 'br': 4.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Do 217 M-1', 'br': 4.7, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 G-14', 'br': 5.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 G-10', 'br': 5.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 A-5/U12', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Fw 190 D-12', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 262 A-1/U4', 'br': 6.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ju 188 A-2', 'br': 5.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Bf 109 K-4', 'br': 5.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ta 152 H-1', 'br': 6.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ta 152 C-3', 'br': 6.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 177 A-5', 'br': 6.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    
    # Rank IV Premium
    {'name': 'He 219 A-7', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Bf 109 Z-1', 'br': 4.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Do 335 B-2', 'br': 5.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Ju 388 J', 'br': 4.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Tempest Mk V', 'br': 5.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Fw 190 C', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Ju 288 C', 'br': 6.0, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    {'name': 'Fw 190 D-13', 'br': 5.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'He 177 A-3', 'br': 6.0, 'type': 'bomber', 'nation': 'germany', 'premium': True},
    
    # Rank V
    {'name': 'Me 262 A-1a', 'br': 7.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 262 C-1a', 'br': 7.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 262 C-2b', 'br': 7.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'He 162 A-2', 'br': 6.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ho 229 V3', 'br': 7.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 262 A-1a/Jabo', 'br': 7.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Ar 234 B-2', 'br': 6.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Ar 234 C-3', 'br': 7.3, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    {'name': 'Me 163 B', 'br': 8.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Me 163 B-0', 'br': 8.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-15bis', 'br': 8.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'IL-28', 'br': 8.0, 'type': 'bomber', 'nation': 'germany', 'premium': False},
    
    # Rank V Premium/Squadron
    {'name': 'Me 262 A-1a/U1', 'br': 7.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'He 162 A-1', 'br': 6.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Sea Hawk Mk.100', 'br': 8.3, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Me 262 A-2a', 'br': 6.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'G.91 R/4', 'br': 8.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    
    # Rank VI
    {'name': 'CL-13A Mk 5', 'br': 8.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'CL-13B Mk.6', 'br': 9.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Lim-5P', 'br': 8.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'G.91 R/3', 'br': 8.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'F-84F', 'br': 8.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Hunter F.58A (1971)', 'br': 9.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'F-86K', 'br': 9.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-19S', 'br': 9.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Alpha Jet A', 'br': 8.7, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-23BN', 'br': 9.7, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    
    # Rank VI Premium/Squadron
    {'name': 'Hunter F.58', 'br': 10.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'FFA P-16', 'br': 9.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'MiG-21 SPS-K', 'br': 9.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    
    # Rank VII
    {'name': 'F-104G', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-21MF', 'br': 10.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-21bis-SAU', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Su-22UM3K', 'br': 11.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Mirage IIIS C.70', 'br': 10.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'F-4F', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-23MLA', 'br': 11.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Su-22M4', 'br': 11.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'F-5E', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    
    # Rank VII Premium
    {'name': 'MiG-21 "Lazur-M"', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'F-4F Early', 'br': 10.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Tornado IDS WTD61', 'br': 11.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'MiG-23MF', 'br': 11.0, 'type': 'fighter', 'nation': 'germany', 'premium': True},
    {'name': 'Su-22M4 WTD61', 'br': 11.0, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    
    # Rank VIII
    {'name': 'F-4F KWS LV', 'br': 13.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-29', 'br': 12.7, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'Tornado IDS ASSTA1', 'br': 11.7, 'type': 'strike fighter', 'nation': 'germany', 'premium': False},
    {'name': 'F/A-18C Late', 'br': 14.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'EF-2000', 'br': 14.3, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    {'name': 'MiG-29G', 'br': 13.0, 'type': 'fighter', 'nation': 'germany', 'premium': False},
    
    # Rank VIII Premium
    {'name': 'Tornado IDS MFG', 'br': 11.3, 'type': 'strike fighter', 'nation': 'germany', 'premium': True},
    {'name': 'F/A-18C', 'br': 12.7, 'type': 'fighter', 'nation': 'germany', 'premium': True},
]

ussr_aircraft = [
    {'name': 'I-16 type 5', 'br': 1.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-15 WR', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-15 M-22', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-15 M-25', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Po-2', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-100A', 'br': 1.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-103', 'br': 2.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-3-15', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-15bis', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-153 M-62', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'BB-1', 'br': 1.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-2 MV-5', 'br': 1.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-2 TSS-1', 'br': 2.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-2 (M-82)', 'br': 2.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-4', 'br': 2.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-16 type 10', 'br': 2.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-16 type 18', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-16 type 24', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-3 (e)', 'br': 2.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-3', 'br': 2.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Ar-2', 'br': 2.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-103U MV-3', 'br': 2.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-105', 'br': 2.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-103U', 'br': 2.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'SB 2M-103 MV-3', 'br': 1.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-2 KABB', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': "Krasnolutsky's I-15bis", 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'MBR-2-M-34', 'br': 1.0, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': '▂PBY-5A Catalina', 'br': 1.7, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': 'Po-2M', 'br': 1.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂Hampden TB Mk I', 'br': 1.7, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': 'TB-3M-17-32', 'br': 1.3, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': 'Tandem MAI', 'br': 1.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': "Zhukovsky's I-153-M62", 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-1', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-1B', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-3-15 (BK)', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-3-34', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'LaGG-3-8', 'br': 2.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'LaGG-3-11', 'br': 2.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-2 (1941)', 'br': 2.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'DB-3B', 'br': 2.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-4', 'br': 2.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-7B', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-16 type 27', 'br': 3.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'LaGG-3-35', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'LaGG-3-66', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-2 (1942)', 'br': 3.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-2-37', 'br': 2.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-2-1', 'br': 3.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-2-31', 'br': 3.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-2-83', 'br': 3.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9B', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-5', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-5F', 'br': 3.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-3bis', 'br': 2.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'LaGG-3-4', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'LaGG-3-23', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-40E-1', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'I-29', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂Hurricane Mk IIB', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'IL-2 M-82', 'br': 2.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'I-153P', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'I-180S', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'I-16 type 28', 'br': 3.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'LaGG-3-34', 'br': 2.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-39K-1', 'br': 2.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'I-301', 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-9T', 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9K', 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-185 (M-82)', 'br': 3.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-5FN', 'br': 3.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-2M (1943)', 'br': 3.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-2M type 3', 'br': 3.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (M-105)', 'br': 3.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (M-105R) LU', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (M-105) TAT', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (M-105R) TAT', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-3', 'br': 4.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9U', 'br': 4.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-185 (M-71)', 'br': 4.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-7', 'br': 4.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-6 (M-71F)', 'br': 4.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-2-110', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-2-359', 'br': 4.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Pe-8', 'br': 4.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': '▂A-20G-30', 'br': 3.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'IL-2M "Avenger"', 'br': 3.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': "▂Pokryshkin's P-39N-0", 'br': 3.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': "Golovachev's Yak-9M", 'br': 3.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-39Q-15', 'br': 3.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Pe-2-205', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-63A-5', 'br': 3.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'IL-8 (1944)', 'br': 3.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-47D-27', 'br': 4.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'TIS MA', 'br': 4.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂B-25J-30', 'br': 3.7, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': 'ITP (M-1)', 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': "Eremin's Yak-3(e)", 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Tu-2', 'br': 4.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-3P', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9P', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'I-225', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-7B-20', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-6 (AM-42)', 'br': 4.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (ACh-30B) (e)', 'br': 4.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yer-2 (ACh-30B) (l)', 'br': 4.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-3U', 'br': 5.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-9UT', 'br': 5.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-9', 'br': 6.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-10', 'br': 5.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-10 (1946)', 'br': 5.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Tu-2S', 'br': 5.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Tu-2S-44', 'br': 5.3, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Tu-2S-59', 'br': 5.7, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-6', 'br': 4.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-63C-5', 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': "Dolgushin's La-7", 'br': 4.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂P-63A-10', 'br': 4.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Be-6', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Su-8', 'br': 4.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'La-11', 'br': 5.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂Fw 190 D-9', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': '▂Spitfire Mk IXc', 'br': 5.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-3T', 'br': 5.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-3 (VK-107)', 'br': 5.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Tu-1', 'br': 5.3, 'type': 'bomber', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-15P', 'br': 6.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-15', 'br': 6.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-17', 'br': 6.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-9', 'br': 7.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-9 (l)', 'br': 7.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-9', 'br': 7.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-28', 'br': 8.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'IL-28Sh', 'br': 8.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Tu-4', 'br': 8.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-23', 'br': 8.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-15', 'br': 8.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-15bis', 'br': 8.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-200', 'br': 7.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'La-15', 'br': 8.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Tu-14T', 'br': 8.0, 'type': 'bomber', 'nation': 'USSR', 'premium': False},
    {'name': '▂L-39ZA Albatros', 'br': 6.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'BI', 'br': 6.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-11', 'br': 7.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'La-174', 'br': 8.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-15bis ISh', 'br': 8.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-30D', 'br': 8.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-17', 'br': 8.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-7B', 'br': 9.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-7BKL', 'br': 9.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-25', 'br': 10.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-28B', 'br': 9.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-38M', 'br': 9.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-19PT', 'br': 9.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-21F-13', 'br': 9.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-17AS', 'br': 9.0, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'MiG-21PFM', 'br': 9.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Yak-38', 'br': 9.3, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Su-7BMK', 'br': 9.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'MiG-21S (R-13-300)', 'br': 9.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Su-25K', 'br': 10.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'MiG-21SMT', 'br': 10.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-21bis', 'br': 11.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-17M2', 'br': 10.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-25T', 'br': 11.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-27M', 'br': 11.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-27K', 'br': 11.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-23M', 'br': 11.0, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-23MLD', 'br': 11.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-17M4', 'br': 11.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-24M', 'br': 11.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-22M3', 'br': 11.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-25BM', 'br': 11.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-23ML', 'br': 11.7, 'type': 'fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Su-39', 'br': 11.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': True},
    {'name': 'Yak-141', 'br': 12.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-29', 'br': 12.7, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-27', 'br': 13.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-25SM3', 'br': 11.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-34', 'br': 13.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'MiG-29SMT', 'br': 13.3, 'type': 'fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-27SM', 'br': 13.7, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-30SM', 'br': 14.3, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
    {'name': 'Su-33', 'br': 13.0, 'type': 'strike fighter', 'nation': 'USSR', 'premium': False},
]

britain_aircraft = [
    # Rank I
    {'name': 'Fury Mk I', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Fury Mk II', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Gladiator Mk IIF', 'br': 1.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Nimrod Mk I', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Chesapeake Mk I', 'br': 1.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'H.P.12', 'br': 1.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Gladiator Mk IIS', 'br': 1.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Nimrod Mk II', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Blenheim Mk IV', 'br': 1.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Beaufort Mk VIII', 'br': 1.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Swordfish Mk I', 'br': 1.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Gladiator Mk II', 'br': 1.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Gladiator Mk I', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Hampden Mk I', 'br': 1.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Hampden TB Mk I', 'br': 1.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    
    # Rank I Premium
    {'name': 'Tuck\'s Gladiator Mk II', 'br': 1.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Swordfish Mk II', 'br': 1.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Wirraway', 'br': 1.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Catalina Mk IIIa', 'br': 1.7, 'type': 'bomber', 'nation': 'britain', 'premium': True},
    
    # Rank II
    {'name': 'Hurricane Mk IIB/Trop', 'br': 2.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Hurricane Mk I/L', 'br': 2.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk Ia', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk IIa', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Hurricane Mk IB', 'br': 2.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Hurricane Mk IV', 'br': 2.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sunderland Mk IIIa', 'br': 1.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Sunderland Mk V', 'br': 2.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Typhoon Mk Ia', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk IIb', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Hurricane Mk IC', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Beaufighter Mk VIc', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Beaufighter Mk X', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Beaufighter Mk 21', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Wellington Mk Ic', 'br': 2.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Wellington Mk Ic/L', 'br': 2.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk Vb/trop', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk Vb', 'br': 4.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Firebrand TF Mk IV', 'br': 3.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Tempest Mk V (Vickers P)', 'br': 3.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Wellington Mk III', 'br': 3.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Wellington Mk X', 'br': 3.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    
    # Rank II Premium
    {'name': 'Avenger Mk II', 'br': 1.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Havoc Mk I', 'br': 2.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Hudson Mk V', 'br': 2.0, 'type': 'bomber', 'nation': 'britain', 'premium': True},
    {'name': 'Beaufighter Mk I (40-mm)', 'br': 2.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Firecrest', 'br': 2.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Boston Mk I', 'br': 2.3, 'type': 'bomber', 'nation': 'britain', 'premium': True},
    {'name': 'Corsair F Mk II', 'br': 2.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'DB-7', 'br': 2.3, 'type': 'bomber', 'nation': 'britain', 'premium': True},
    {'name': 'Spitfire Mk.IIa Venture I', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Hurricane Mk.I/L FAA M', 'br': 2.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'D.520', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Martlet Mk IV', 'br': 2.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'D.521', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Boomerang Mk I', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Boomerang Mk II', 'br': 3.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    
    # Rank III
    {'name': 'Typhoon Mk Ib/L', 'br': 4.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk IX', 'br': 4.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk XVI', 'br': 5.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Firefly F Mk I', 'br': 3.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Firefly FR Mk V', 'br': 3.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Mosquito FB Mk VI', 'br': 3.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Mosquito FB Mk XVIII', 'br': 3.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Mosquito NF.Mk.II', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Mosquito TR.Mk.33', 'br': 3.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Halifax B Mk IIIa', 'br': 4.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk Vc/trop', 'br': 4.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire Mk Vc', 'br': 5.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Seafire LF Mk.III', 'br': 5.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Brigand B 1', 'br': 4.0, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Whirlwind Mk I', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Stirling B Mk I', 'br': 4.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Stirling B Mk III', 'br': 4.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    
    # Rank III Premium
    {'name': 'Hellcat Mk II', 'br': 3.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Typhoon Mk Ib', 'br': 4.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Thunderbolt Mk.1', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Whirlwind P.9', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Mustang Mk IA', 'br': 3.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Spitfire F Mk IXc', 'br': 4.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    
    # Rank IV
    {'name': 'Tempest Mk V', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk XIVe', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk XVIIIe', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire LF Mk IX', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Seafire F Mk XVII', 'br': 5.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Seafire FR 47', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Hornet Mk.III', 'br': 6.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Lancaster B Mk I', 'br': 5.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Lancaster B Mk III', 'br': 5.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Tempest Mk II', 'br': 6.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk 22', 'br': 6.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Spitfire F Mk 24', 'br': 6.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Fury FB 11', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Lincoln B Mk II', 'br': 6.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Shackleton MR.Mk.2', 'br': 6.0, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    
    # Rank IV Premium
    {'name': 'MB.5', 'br': 5.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Wyvern S.4', 'br': 4.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Hornet Mk.I', 'br': 6.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Spitfire F Mk XIVc', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Plagis\' Spitfire LF Mk IXc', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Prendergast\'s Spitfire FR Mk XIVe', 'br': 5.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Strikemaster Mk.88', 'br': 6.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    
    # Rank V
    {'name': 'Vampire F.B.5', 'br': 8.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Meteor F Mk 3', 'br': 7.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Meteor F Mk 3', 'br': 7.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Attacker FB 1', 'br': 7.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Swift F.1', 'br': 8.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Canberra B Mk 2', 'br': 8.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Canberra B (I) Mk 6', 'br': 8.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Venom FB.4', 'br': 8.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Meteor F Mk 4 G.41F', 'br': 7.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Meteor F Mk 4 G.41G', 'br': 8.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Meteor F Mk 8 G.41K', 'br': 8.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Hawk FGA.6', 'br': 8.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Venom FAW 20', 'br': 7.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Swift F.7', 'br': 8.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    
    # Rank V Premium
    {'name': 'Meteor F Mk.8 Reaper', 'br': 8.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Attacker FB.2', 'br': 7.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Sea Vixen F.A.W. Mk.2', 'br': 9.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'HF-24', 'br': 9.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    
    # Rank VI
    {'name': 'Hunter F.1', 'br': 8.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Javelin F.(A.W.) Mk.9', 'br': 8.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Scimitar F Mk.1', 'br': 8.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Jaguar GR.1', 'br': 9.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Buccaneer S.2', 'br': 9.3, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Hunter F.6', 'br': 9.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Lightning F.6', 'br': 9.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Harrier GR.3', 'br': 9.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    
    # Rank VI Premium
    {'name': 'Lightning F.53', 'br': 9.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Buccaneer S.1', 'br': 8.7, 'type': 'bomber', 'nation': 'britain', 'premium': True},
    {'name': 'Harrier GR.1', 'br': 9.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Hunter FGA.9', 'br': 9.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    
    # Rank VII
    {'name': 'Phantom FGR.2', 'br': 12.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Harrier FRS.1 (e)', 'br': 10.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Jaguar GR.1A', 'br': 10.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Buccaneer S.2B', 'br': 10.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    {'name': 'Phantom FG.1', 'br': 12.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'F-111C', 'br': 11.7, 'type': 'bomber', 'nation': 'britain', 'premium': False},
    
    # Rank VII Premium/Squadron
    {'name': 'Sea Harrier FRS.1', 'br': 11.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Jaguar IS', 'br': 11.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    {'name': 'F-4J(UK) Phantom II', 'br': 12.0, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'Harrier T.10', 'br': 11.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': True},
    
    # Rank VIII
    {'name': 'JAS39C', 'br': 13.7, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Tornado F.3', 'br': 12.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'F/A-18A', 'br': 12.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Harrier GR.7', 'br': 12.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Tornado GR.1', 'br': 11.7, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Typhoon FGR.4', 'br': 14.3, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Tornado F.3 Late', 'br': 13.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Sea Harrier FA 2', 'br': 13.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    {'name': 'Tornado GR.4', 'br': 12.3, 'type': 'strike fighter', 'nation': 'britain', 'premium': False},
    {'name': 'AF/A-18A Late', 'br': 14.0, 'type': 'fighter', 'nation': 'britain', 'premium': False},
    
    # Rank VIII Premium
    {'name': 'MiG-21 Bison', 'br': 12.3, 'type': 'fighter', 'nation': 'britain', 'premium': True},
    {'name': 'CF-188A', 'br': 12.7, 'type': 'fighter', 'nation': 'britain', 'premium': True},
]

japan_aircraft = [
    {'name': 'F1M2', 'br': 1.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-10-I', 'br': 1.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-10-II', 'br': 1.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-10-I C', 'br': 1.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-10-II C', 'br': 1.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-45 Tei', 'br': 1.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-45 Otsu', 'br': 2.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'B5N2', 'br': 1.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-32', 'br': 1.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A5M4', 'br': 1.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-27 Otsu', 'br': 2.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-45 Ko', 'br': 2.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-45 Hei', 'br': 2.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'D3A1', 'br': 1.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-21-Ia', 'br': 1.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-43-I', 'br': 2.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-43-II', 'br': 2.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-109', 'br': 2.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'B6N1 Model 11', 'br': 1.7, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'H6K4', 'br': 1.7, 'type': 'bomber', 'nation': 'Japan', 'premium': False},
    {'name': "Hagiri's A5M4", 'br': 1.3, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-27 Otsu Tachiarai', 'br': 2.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A6M2-N', 'br': 2.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'N1K1', 'br': 2.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-44-I', 'br': 2.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-61-I Ko', 'br': 3.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J1N1', 'br': 2.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'B6N2 Model 12', 'br': 2.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'B6N2a Model 12Ko', 'br': 2.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'G4M1', 'br': 2.7, 'type': 'bomber', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M2 mod. 11', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M2', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-44-II Hei', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-61-I Otsu', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-102 Otsu', 'br': 3.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'D4Y1', 'br': 2.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'D4Y2', 'br': 2.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'H8K2', 'br': 3.7, 'type': 'bomber', 'nation': 'Japan', 'premium': False},
    {'name': 'D4Y3 Ko', 'br': 3.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-49-I', 'br': 3.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-49-IIa', 'br': 3.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A7He1', 'br': 2.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-48-II Otsu', 'br': 2.3, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-44-I 34', 'br': 2.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-21-I Hei', 'br': 2.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-44-II Otsu', 'br': 3.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': '▅Bf 109 E-7', 'br': 3.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'H8K3', 'br': 4.0, 'type': 'bomber', 'nation': 'Japan', 'premium': True},
    {'name': '▅F4U-1A', 'br': 3.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A6M3', 'br': 4.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M3 mod. 22', 'br': 4.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M3 mod. 22Ko', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-43-III Otsu', 'br': 4.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-108 Kai', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'P1Y1 mod. 11', 'br': 3.3, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-49-IIb', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-49-IIb/L', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M5', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-61-I Tei', 'br': 4.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-61-II Otsu Kai', 'br': 4.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J2M2', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'B7A2', 'br': 3.7, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'G5N1', 'br': 4.3, 'type': 'bomber', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-100', 'br': 4.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J5N1', 'br': 5.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-67-I Ko', 'br': 4.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-67-I Otsu', 'br': 4.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-96', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': '▅P-51C-11-NT', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-100-II', 'br': 3.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'B7A2 (Homare 23)', 'br': 3.7, 'type': 'strike fighter', 'nation': 'Japan', 'premium': True},
    {'name': '▄SB2C-5', 'br': 3.7, 'type': 'strike fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A6M5 Otsu', 'br': 5.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'A6M5 Hei', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-61-I Hei', 'br': 4.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J7W1', 'br': 6.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'G8N1', 'br': 6.3, 'type': 'bomber', 'nation': 'Japan', 'premium': False},
    {'name': 'A7M2', 'br': 5.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-84 Ko', 'br': 5.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-84 Otsu', 'br': 5.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J2M3', 'br': 5.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J2M5', 'br': 5.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'N1K1-Ja', 'br': 5.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'N1K2-J', 'br': 6.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'N1K2-Ja', 'br': 6.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-84 Hei', 'br': 6.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-83', 'br': 6.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▅B-17E', 'br': 4.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A6M6c', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A7M1 (NK9H)', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'A6M5 Ko', 'br': 5.3, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': "Tada's Ki-61-I Hei", 'br': 4.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': '▅Fw 190 A-5', 'br': 4.3, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'J2M4 Kai', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-94-II', 'br': 6.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'J2M5 (Type 5)', 'br': 5.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'J6K1', 'br': 6.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Ki-87', 'br': 5.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'Kikka', 'br': 7.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'Ki-200', 'br': 8.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-84G-21-RE', 'br': 7.7, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'R2Y2 Kai V1', 'br': 8.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'R2Y2 Kai V2', 'br': 8.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'R2Y2 Kai V3', 'br': 8.0, 'type': 'strike fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-86F-30 ▅', 'br': 8.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-86F-40 ▅', 'br': 9.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-86F-40 JASDF▅', 'br': 9.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'F-104J', 'br': 10.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'T-2', 'br': 9.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄Alpha Jet A', 'br': 8.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-1', 'br': 10.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄Alpha Jet TH', 'br': 10.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'T-2 Early', 'br': 9.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': '▄AV-8S', 'br': 9.7, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'F-4EJ Phantom II', 'br': 11.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄A-7E', 'br': 10.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-5A', 'br': 10.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄AV-8S Late', 'br': 11.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-5T SCU', 'br': 11.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-5E FCU', 'br': 11.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-4EJ ADTW', 'br': 11.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
    {'name': 'F-4EJ Kai Phantom II', 'br': 12.3, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-16AJ', 'br': 12.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-5TH TCU', 'br': 13.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-15J', 'br': 13.0, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-2A', 'br': 13.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄F-16A OCU', 'br': 13.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-15J(M)', 'br': 13.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': '▄JAS39C', 'br': 13.7, 'type': 'fighter', 'nation': 'Japan', 'premium': False},
    {'name': 'F-2A ADTW', 'br': 13.0, 'type': 'fighter', 'nation': 'Japan', 'premium': True},
]

china_aircraft = []

italy_aircraft = []

france_aircraft = []

sweden_aircraft = []

israel_aircraft = []