# Speed Skills
speed_skills = {
    "[Run Style] Corners ◯": ("◎", "◎"),
    "[Run Style] Corners ◎": ("△", "◎"),
    "[Run Style] Straightaways ◯": ("◎", "◎"),
    "[Run Style] Straightaways ◎": ("△", "◎"),
    "[Distance] Corners ◯": ("◎", "◎"),
    "[Distance] Corners ◎": ("△", "◎"),
    "[Distance] Straightaways ◯": ("◎", "◎"),
    "[Distance] Straightaways ◎": ("△", "◎"),
    "Corner Adept ◯": ("◯", "◯"),
    "Professor of Curvature": ("◎", "◎"),
    "Straightaway Adept": ("△", "△"),
    "Beeline Burst": ("△", "△"),
    "Ramp Up": ("◎", "◎"),
    "It's On!": ("◎", "◎"),
    "Homestretch Haste": ("◯", "◯"),
    "In Body and Mind": ("◯", "◯"),
    "Uma Stan": ("△", "✕"),
    "Uma Mania": ("△", "✕"),
    "Tail Held High": ("◎", "◎"),
    "Slipstream": ("◎", "◎"),
    "Playtime's Over!": ("◎", "◎"),
    "Fast-Paced": ("◎", "◎"),
    "Escape Artist": ("◎", "◎"),
    "Leader's Pride": ("✕", "✕"),
    "Prepared to Pass": ("△", "◯"),
    "Speed Star": ("△", "◯"),
    "Position Pilfer": ("△", "◯"),
    "Fast & Furious": ("△", "◯"),
    "Outer Swell": ("△", "◎"),
    "Rising Dragon": ("△", "◎"),
    "1,500,000 CC": ("◎", "◎"),
    "Masterful Gambit": ("✕", "✕"),
    "Sturm und Drang": ("✕", "✕"),
    "Gap Closer": ("▲", "✕"),
    "Blinding Flash": ("▲", "✕"),
    "Huge Lead": ("✕", "✕"),
    "Staggering Lead": ("✕", "✕"),
    "Productive Plan": ("✕", "✕"),
    "Mile Maven": ("✕", "✕"),
    "Shifting Gears": ("△", "◯"),
    "Changing Gears": ("△", "◯"),
    "Unyielding Spirit": ("◎", "◎"),
    "Big-Sisterly": ("◎", "◎"),
    "Up-Tempo": ("△", "✕"),
    "Killer Tunes": ("△", "✕"),
    "Steadfast": ("△", "✕"),
    "Unyielding": ("△", "✕"),
    "Inside Scoop": ("△", "✕"),
    "Innate Experience": ("△", "✕"),
    "Keeping the Lead": ("✕", "✕"),
    "Vanguard Spirit": ("✕", "✕"),
    "Pressure": ("△", "✕"),
    "Overwhelming Pressure": ("△", "✕"),
    "Top Pick": ("△", "✕"),
    "Trending in the Charts!": ("△", "✕"),
    "Certain Victory": ("△", "◯"),
    "Legacy of the Strong": ("✕", "✕"),
    "Shooting Star": ("△", "✕"),
    "The View from the Lead is Mine!": ("△", "✕"),
    "Sky-High Teio Step": ("△", "◯"),
    "Triumphant Pulse": ("△", "◯"),
    "Anchors Aweigh!": ("△", "✕"),
    "Cut and Drive!": ("✕", "✕"),
    "Resplendent Red Ace": ("△", "▲"),
    "Where There's a Will, There's a Way": ("✕", "✕"),
    "The Duty of Dignity Calls": ("△", "◯"),
    "Victoria por plancha ☆": ("✕", "◎"),
    "This Dance Is for Vittoria!": ("✕", "△"),
    "Behold Thine Emperor's Divine Might": ("△", "◎"),
    "Blazing Pride": ("△", "▲"),
    "∴win Q.E.D.": ("△", "▲"),
    "Flashy☆Landing": ("△", "✕"),
    "G00 1st. F∞;": ("✕", "✕"),
    "Blue Rose Closer": ("△", "✕"),
    "Our Ticket to Win!": ("✕", "✕"),
    "Genius x Bakushin = Victory": ("△", "▲"),
    "I See Victory in My Future!": ("✕", "✕"),
    "Just a Little Farther!": ("△", "✕"),
    "Prideful King": ("✕", "✕"),
    "#LookatCurren": ("△", "✕"),
    "Nemesis": ("△", "△"),
    "SPARKLY☆STARDOM": ("△", "▲"),
    "Shadow Break": ("△", "△"),
    "Eternal Moments": ("△", "△"),
    "Flowery☆Maneuver": ("△", "▲")
}

# Acceleration Skills
acceleration_skills = {
    "Corner Acceleration ◯": ("△", "✕"),
    "Corner Connoisseur": ("△", "✕"),
    "Straightaway Acceleration": ("△", "✕"),
    "Rushing Gale!": ("△", "✕"),
    "Nimble Navigator": ("◯", "◎"),
    "No Stopping Me!": ("◯", "◎"),
    "Highlander": ("△", "◯"),
    "Groundwork": ("△", "▲"),
    "Ignited Spirit PWR": ("◎", "◎"),
    "Burning Spirit PWR": ("◎", "◎"),
    "Early Lead": ("◎", "⍟"),
    "Taking the Lead": ("◎", "⍟"),
    "Final Push": ("△", "◎"),
    "Unrestrained": ("△", "◎"),
    "Second Wind": ("✕", "✕"),
    "Shrewd Step": ("△", "✕"),
    "Technician": ("△", "✕"),
    "Straight Descent": ("△", "⍟"),
    "Determined Descent": ("△", "⍟"),
    "Tactical Tweak": ("△", "✕"),
    "Shatterproof": ("△", "✕"),
    "Head-On": ("◯", "⍟"),
    "Slick Surge": ("◯", "⍟"),
    "On Your Left!": ("◯", "⍟"),
    "Fighter": ("△", "✕"),
    "Hard Worker": ("△", "✕"),
    "Straightaway Spurt": ("△", "⍟"),
    "Encroaching Shadow": ("△", "⍟"),
    "Sprinting Gear": ("△", "✕"),
    "Turbo Sprint": ("△", "✕"),
    "Countermeasure": ("△", "✕"),
    "Plan X": ("△", "✕"),
    "Updrafters": ("◯", "◎"),
    "Furious Feat": ("◯", "◎"),
    "Acceleration": ("△", "✕"),
    "Step on the Gas!": ("△", "✕"),
    "Red Shift/LP1211-M": ("▲", "✕"),
    "Shooting for Victory!": ("▲", "◎"),
    "Let's Pump Some Iron!": ("▲", "◎"),
    "Angling and Scheming": ("▲", "⍟"),
    "Condor's Fury": ("▲", "✕"),
    "KEEP IT REAL.": ("△", "✕")
}

# Stamina Skills
stamina_skills = {
    "Corner Recovery ◯": ("◎", "◎"),
    "Swinging Maestro": ("◎", "◎"),
    "Straightaway Recovery": ("△", "△"),
    "Breath of Fresh Air": ("△", "△"),
    "Lay Low": ("△", "✕"),
    "Iron Will": ("△", "✕"),
    "Pace Strategy": ("△", "✕"),
    "Indomitable": ("△", "✕"),
    "Calm in a Crowd": ("✕", "✕"),
    "Unruffled": ("✕", "✕"),
    "Triple 7s": ("△", "▲"),
    "Shake It Out": ("△", "✕"),
    "Ignited Spirit STA": ("△", "△"),
    "Burning Spirit STA": ("△", "△"),
    "Moxie": ("△", "◯"),
    "Restless": ("△", "△"),
    "Stamina to Spare": ("△", "◯"),
    "Calm and Collected": ("△", "◎"),
    "Preferred Position": ("◎", "◯"),
    "Race Planner": ("◎", "◎"),
    "Hydrate": ("◎", "◯"),
    "Gourmand": ("◎", "◎"),
    "A Small Breather": ("△", "✕"),
    "Relax": ("△", "✕"),
    "Standing By": ("△", "✕"),
    "Sleeping Lion": ("△", "✕"),
    "After-School Stroll": ("△", "✕"),
    "Go-Home Specialist": ("△", "✕"),
    "Levelheaded": ("△", "△"),
    "Wait-and-See": ("▲", "✕"),
    "Watchful Eye": ("▲", "⍟"),
    "Keen Eye": ("▲", "⍟"),
    "Rosy Outlook": ("△", "✕"),
    "Trackblazer": ("△", "✕"),
    "Soft Step": ("△", "✕"),
    "Miraculous Step": ("△", "✕"),
    "Deep Breaths": ("△", "✕"),
    "Cooldown": ("△", "✕"),
    "Extra Tank": ("✕", "✕"),
    "Adrenaline Rush": ("✕", "✕"),
    "Passing Pro": ("△", "✕"),
    "U=ma2": ("△", "✕"),
    "Pure Heart": ("△", "△"),
    "Super-Duper Climax": ("△", "✕"),
    "Superior Heal": ("△", "△"),
    "Dazzl'n ♪ Diver": ("△", "✕")
}

# Debuff Skills
debuff_skills = {
    "Hesitant [Run Style]s": ("◎", "◎"),
    "Frenzied [Run Style]s": ("◯", "◎"),
    "Subdued [Run Style]s": ("◎", "◎"),
    "Flustered [Run Style]s": ("◎", "◎"),
    "Trick (Front)": ("◎", "◎"),
    "Trick (Rear)": ("◎", "◎"),
    "Restart": ("✕", "✕"),
    "Disorient": ("△", "✕"),
    "Dazzling Disorientation": ("△", "✕"),
    "Sharp Gaze": ("◎", "◎"),
    "All-Seeing Eyes": ("◎", "◎"),
    "Intense Gaze": ("△", "◯"),
    "Intimidate": ("△", "✕"),
    "Adored by All": ("△", "✕"),
    "Stop Right There!": ("✕", "✕"),
    "Speed Eater": ("△", "△"),
    "Opening Gambit": ("✕", "△"),
    "Tether": ("◎", "✕"),
    "Dominator": ("◎", "✕"),
    "Murmur": ("◎", "✕"),
    "Mystifying Murmur": ("◎", "✕"),
    "Stamina Eater": ("◯", "✕"),
    "Stamina Siphon": ("◎", "✕"),
    "Smoke Screen": ("△", "✕"),
    "Illusionist": ("△", "✕")
}

# Other Skills (Lane Movement/FoV/Start Skills)
other_skills = {
    "Prudent Positioning": ("△", "▲"),
    "Center Stage": ("△", "✕"),
    "Go with the Flow": ("△", "✕"),
    "Lane Legerdemain": ("△", "✕"),
    "Ignited Spirit WIT": ("△", "▲"),
    "Burning Spirit WIT": ("△", "✕"),
    "Dodging Danger": ("△", "⍟"),
    "Sixth Sense": ("△", "✕"),
    "Meticulous Measures": ("△", "✕"),
    "Perfect Prep!": ("△", "✕"),
    "Thunderbolt Step": ("△", "✕"),
    "Lightning Step": ("△", "✕"),
    "Focus": ("◎", "▲"),
    "Concentration": ("◎", "▲"),
    "Studious": ("△", "✕"),
    "The Bigger Picture": ("△", "✕"),
    "I Can See Right Through You": ("△", "✕"),
    "The Coast Is Clear!": ("△", "✕"),
    "Strategist": ("△", "✕"),
    "Crusader": ("△", "✕"),
    "Hawkeye": ("△", "✕"),
    "Clairvoyance": ("△", "✕"),
    "Runaway": ("▲", "▲"),

    # Green Skills
    "[Rotation]-Handed ◯": ("◯", "◎"),
    "[Rotation]-Handed ◎": ("✕", "◎"),
    "[Season] Runner ◯": ("◯", "◎"),
    "[Season] Runner ◎": ("✕", "◎"),
    "Outer Post Proficiency ◯": ("✕", "✕"),
    "Outer Post Proficiency ◎": ("✕", "✕"),
    "Maverick ◯": ("✕", "✕"),
    "Maverick ◎": ("✕", "✕"),
    "Long Shot ◯": ("✕", "✕"),
    "Long Shot ◎": ("✕", "✕"),
    "Sympathy": ("✕", "▲"),
    "Lone Wolf": ("◎", "◎"),
    "[Location] Racecourse ◯": ("△", "◎"),
    "[Location] Racecourse ◎": ("✕", "◎"),
    "Standard Distance ◯": ("◯", "◎"),
    "Standard Distance ◎": ("✕", "◎"),
    "Non-Standard Distance ◯": ("◯", "◎"),
    "Non-Standard Distance ◎": ("✕", "◎"),
    "[Ground Condition] Conditions ◯": ("△", "◎"),
    "[Ground Condition] Conditions ◎": ("✕", "◎"),
    "Competitive Spirit ◯": ("✕", "✕"),
    "Competitive Spirit ◎": ("✕", "✕"),
    "[Weather] Days ◯": ("△", "△"),
    "[Weather] Days ◎": ("✕", "△"),
    "Target in Sight ◯": ("✕", "✕"),
    "Target in Sight ◎": ("✕", "✕"),
    "Inner Post Proficiency ◯": ("✕", "✕"),
    "Inner Post Proficiency ◎": ("✕", "✕"),
    "[Run Style] Savvy ◯": ("◎", "◯"),
    "[Run Style] Savvy ◎": ("✕", "▲"),
    "Lucky Seven": ("✕", "✕"),
    "Super Lucky Seven": ("✕", "✕")
}
